// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IArticleFields {
  /** Title */
  title: string;

  /** slug */
  slug?: string | undefined;

  /** Description */
  description: string;

  /** Content */
  content?: Document | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Action */
  action?: string | undefined;

  /** Url */
  url: string;

  /** Author */
  author: string;
}

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "article";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMainFields {
  /** Title */
  title?: string | undefined;

  /** Desctiption */
  description?: Document | undefined;

  /** Subtitle */
  subtitle?: string | undefined;

  /** Background */
  background?: Asset | undefined;
}

export interface IMain extends Entry<IMainFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "main";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Internal name */
  name: string;

  /** Page title */
  title: string;

  /** Slug */
  slug: string;

  /** SEO metadata */
  seo?: ISeo | undefined;

  /** Content */
  content:
    | IPageLanding
    | IPageHelpCenterArticle
    | IPageMytrialblogapi
    | IPageBlog;
}

/** Represents a web page in Compose. DO NOT DELETE */

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageBlogFields {
  /** Internal Name */
  name?: string | undefined;
}

export interface IPageBlog extends Entry<IPageBlogFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageBlog";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageMytrialblogapiFields {
  /** Internal Name */
  name?: string | undefined;

  /** My Company Blogs */
  myCompanyBlogs?: string | undefined;
}

/** Trial blogs to check how it works */

export interface IPageMytrialblogapi extends Entry<IPageMytrialblogapiFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageMytrialblogapi";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISeoFields {
  /** Internal name */
  name: string;

  /** SEO title */
  title?: string | undefined;

  /** Description */
  description?: string | undefined;

  /** Keywords */
  keywords?: string[] | undefined;

  /** Hide page from search engines (noindex) */
  no_index?: boolean | undefined;

  /** Exclude links from search rankings? (nofollow) */
  no_follow?: boolean | undefined;
}

/** SEO Metadata for web pages in Compose. DO NOT DELETE */

export interface ISeo extends Entry<ISeoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "seo";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "article"
  | "main"
  | "page"
  | "pageBlog"
  | "pageMytrialblogapi"
  | "seo";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
